In [2]:
    import os
    import numpy as np
    from tensorflow.keras.models import Sequential, load_model
    from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, GRU, TimeDistributed
    from tensorflow.keras.preprocessing.image import ImageDataGenerator

    # Set the path to your dataset
    train_data_dir = r"D:\new smote\train-20230326T152931Z-001\train"

    # Specify image dimensions and batch size
    img_width, img_height = 150, 150
    batch_size = 32

    # Extract class names from the folder names
    class_names = sorted(os.listdir(train_data_dir))

    # Create data generator for training data
    train_datagen = ImageDataGenerator(
        rescale=1. / 255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

    train_generator = train_datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode='sparse',
        shuffle=False)  # Disable shuffling to maintain the order of images

    # Reshape the input data to include a time dimension
    X_train_reshaped = []
    y_train = []

    for i in range(len(train_generator)):
        images, labels = train_generator[i]
        for j in range(len(images)):
            X_train_reshaped.append(images[j])
            y_train.append(labels[j])

    X_train_reshaped = np.array(X_train_reshaped)
    y_train = np.array(y_train, dtype=np.int32)

    # Add a time dimension to the input data
    X_train_reshaped = np.expand_dims(X_train_reshaped, axis=1)

    # Define the GRU model
    model = Sequential()
    model.add(TimeDistributed(Conv2D(32, (3, 3), activation='relu'), input_shape=(1, img_width, img_height, 3)))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Conv2D(64, (3, 3), activation='relu')))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Conv2D(128, (3, 3), activation='relu')))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Flatten()))
    model.add(GRU(128, activation='relu', return_sequences=False))
    model.add(Dense(len(class_names), activation='softmax'))

    # Compile the model
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    # Train the model
    model.fit(
        X_train_reshaped,
        y_train,
        batch_size=batch_size,
        epochs=30,
        steps_per_epoch=312)

    # Save the trained model
    model.save('lung_detection_grunot30.h5')

    # Set the path to your test dataset
    test_data_dir = r"D:\new smote\test-20230326T155708Z-001\test"

    # Create data generator for test data
    test_datagen = ImageDataGenerator(rescale=1. / 255)

    test_generator = test_datagen.flow_from_directory(
        test_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode='sparse',
        shuffle=False)  # Disable shuffling to maintain the order of images

    # Reshape the input data to include a time dimension
    X_test_reshaped = []
    y_test = []

    for i in range(len(test_generator)):
        images, labels = test_generator[i]
        for j in range(len(images)):
            X_test_reshaped.append(images[j])
            y_test.append(labels[j])

    X_test_reshaped = np.array(X_test_reshaped)
    y_test = np.array(y_test, dtype=np.int32)

    # Add a time dimension to the input data
    X_test_reshaped = np.expand_dims(X_test_reshaped, axis=1)

    # Load the trained model
    model = load_model('lung_detection_grunot30.h5')

    # Evaluate the model on the test data
    loss, accuracy = model.evaluate(X_test_reshaped, y_test)
    print(f"Test loss: {loss}")
    print(f"Test accuracy: {accuracy}")


Found 16050 images belonging to 6 classes.


C:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\core\wrapper.py:27: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 205s 637ms/step - accuracy: 0.4900 - loss: 1.3164
Epoch 2/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 121s 386ms/step - accuracy: 0.6919 - loss: 0.8206
Epoch 3/30


C:\ProgramData\anaconda3\Lib\contextlib.py:155: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


312/312 ━━━━━━━━━━━━━━━━━━━━ 191s 612ms/step - accuracy: 0.7625 - loss: 0.6542
Epoch 4/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 122s 389ms/step - accuracy: 0.7881 - loss: 0.5739
Epoch 5/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 193s 617ms/step - accuracy: 0.8268 - loss: 0.4525
Epoch 6/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 118s 379ms/step - accuracy: 0.8411 - loss: 0.4420
Epoch 7/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 204s 653ms/step - accuracy: 0.8970 - loss: 0.2919
Epoch 8/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 246s 789ms/step - accuracy: 0.8864 - loss: 0.3228
Epoch 9/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 389s 1s/step - accuracy: 0.9253 - loss: 0.1965
Epoch 10/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 233s 744ms/step - accuracy: 0.9139 - loss: 0.2303
Epoch 11/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 380s 1s/step - accuracy: 0.9402 - loss: 0.1673
Epoch 12/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 231s 739ms/step - accuracy: 0.9459 - loss: 0.1488
Epoch 13/30
312/312 ━━━━━━━━━━━━━━━━━━━━ 378s 1s/step - accuracy: 0.9633 - loss: 0.1081
Epoch 14/30
312/312 ━━━━━━

Found 4110 images belonging to 6 classes.


129/129 ━━━━━━━━━━━━━━━━━━━━ 37s 243ms/step - accuracy: 0.7722 - loss: 1.9722
Test loss: 1.8118077516555786
Test accuracy: 0.7710462212562561


In [4]:
# Load the trained model
from sklearn.metrics import classification_report, confusion_matrix
model = load_model('lung_detection_grunot30.h5')

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(f"Test loss: {loss}")
print(f"Test accuracy: {accuracy}")

# Get the raw predictions for the test data
y_pred_probs = model.predict(X_test_reshaped)

# Convert the predicted probabilities to class labels
y_pred = np.argmax(y_pred_probs, axis=1)

# Get the class labels
labels = test_generator.class_indices

# Generate the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=labels))

# Generate the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


129/129 ━━━━━━━━━━━━━━━━━━━━ 41s 270ms/step - accuracy: 0.7722 - loss: 1.9722
Test loss: 1.8118077516555786
Test accuracy: 0.7710462212562561
129/129 ━━━━━━━━━━━━━━━━━━━━ 37s 270ms/step

Classification Report:
              precision    recall  f1-score   support

CARDIOMEGALY       0.84      0.78      0.81       685
       COVID       0.78      0.66      0.71       685
      NORMAL       0.77      0.76      0.77       685
   PNEUMONIA       0.89      0.88      0.88       685
PNEUMOTHORAX       0.54      0.73      0.62       685
TUBERCULOSIS       0.91      0.82      0.86       685

    accuracy                           0.77      4110
   macro avg       0.79      0.77      0.78      4110
weighted avg       0.79      0.77      0.78      4110


Confusion Matrix:
[[533  33   3   4 109   3]
 [ 34 451  35   6 127  32]
 [ 13  11 521  51  88   1]
 [  4  14  36 600  24   7]
 [ 33  50  75  14 503  10]
 [ 20  21   7   0  76 561]]


In [6]:
    import os
    import numpy as np
    from tensorflow.keras.models import Sequential, load_model
    from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, GRU, TimeDistributed
    from tensorflow.keras.preprocessing.image import ImageDataGenerator

    # Set the path to your dataset
    train_data_dir = r"D:\new smote\train-20230326T152931Z-001\train"

    # Specify image dimensions and batch size
    img_width, img_height = 150, 150
    batch_size = 32

    # Extract class names from the folder names
    class_names = sorted(os.listdir(train_data_dir))

    # Create data generator for training data
    train_datagen = ImageDataGenerator(
        rescale=1. / 255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

    train_generator = train_datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode='sparse',
        shuffle=False)  # Disable shuffling to maintain the order of images

    # Reshape the input data to include a time dimension
    X_train_reshaped = []
    y_train = []

    for i in range(len(train_generator)):
        images, labels = train_generator[i]
        for j in range(len(images)):
            X_train_reshaped.append(images[j])
            y_train.append(labels[j])

    X_train_reshaped = np.array(X_train_reshaped)
    y_train = np.array(y_train, dtype=np.int32)

    # Add a time dimension to the input data
    X_train_reshaped = np.expand_dims(X_train_reshaped, axis=1)

    # Define the GRU model
    model = Sequential()
    model.add(TimeDistributed(Conv2D(32, (3, 3), activation='relu'), input_shape=(1, img_width, img_height, 3)))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Conv2D(64, (3, 3), activation='relu')))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Conv2D(128, (3, 3), activation='relu')))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Flatten()))
    model.add(GRU(128, activation='relu', return_sequences=False))
    model.add(Dense(len(class_names), activation='softmax'))

    # Compile the model
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    # Train the model
    model.fit(
        X_train_reshaped,
        y_train,
        batch_size=batch_size,
        epochs=20,
        steps_per_epoch=312)

    # Save the trained model
    model.save('lung_detection_grunot20.h5')

    # Set the path to your test dataset
    test_data_dir = r"D:\new smote\test-20230326T155708Z-001\test"

    # Create data generator for test data
    test_datagen = ImageDataGenerator(rescale=1. / 255)

    test_generator = test_datagen.flow_from_directory(
        test_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode='sparse',
        shuffle=False)  # Disable shuffling to maintain the order of images

    # Reshape the input data to include a time dimension
    X_test_reshaped = []
    y_test = []

    for i in range(len(test_generator)):
        images, labels = test_generator[i]
        for j in range(len(images)):
            X_test_reshaped.append(images[j])
            y_test.append(labels[j])

    X_test_reshaped = np.array(X_test_reshaped)
    y_test = np.array(y_test, dtasktype=np.int32)

    # Add a time dimension to the input data
    X_test_reshaped = np.expand_dims(X_test_reshaped, axis=1)

    # Load the trained model
    model = load_model('lung_detection_grunot20.h5')

    # Evaluate the model on the test data
    loss, accuracy = model.evaluate(X_test_reshaped, y_test)
    print(f"Test loss: {loss}")
    print(f"Test accuracy: {accuracy}")


Found 16050 images belonging to 6 classes.
Epoch 1/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 223s 604ms/step - accuracy: 0.4837 - loss: 1.3135
Epoch 2/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 141s 453ms/step - accuracy: 0.6736 - loss: 0.8835
Epoch 3/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 177s 567ms/step - accuracy: 0.7309 - loss: 0.7291
Epoch 4/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 106s 340ms/step - accuracy: 0.7580 - loss: 0.6708
Epoch 5/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 179s 574ms/step - accuracy: 0.8311 - loss: 0.4779
Epoch 6/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 105s 337ms/step - accuracy: 0.8231 - loss: 0.4838
Epoch 7/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 174s 558ms/step - accuracy: 0.8853 - loss: 0.3233
Epoch 8/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 106s 339ms/step - accuracy: 0.8772 - loss: 0.3332
Epoch 9/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 174s 557ms/step - accuracy: 0.9253 - loss: 0.2171
Epoch 10/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 106s 338ms/step - accuracy: 0.9156 - loss: 0.2317
Epoch 11/20
312/312 ━━━━━━━━━━━━━━━━━━━━ 175s 561ms/step

Found 4110 images belonging to 6 classes.


TypeError: array() got an unexpected keyword argument 'dtasktype'

In [11]:
    # Set the path to your test dataset
    test_data_dir = r"D:\new smote\test-20230326T155708Z-001\test"

    # Create data generator for test data
    test_datagen = ImageDataGenerator(rescale=1. / 255)

    test_generator = test_datagen.flow_from_directory(
        test_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode='sparse',
        shuffle=False)  # Disable shuffling to maintain the order of images

    # Reshape the input data to include a time dimension
    X_test_reshaped = []
    y_test = []

    for i in range(len(test_generator)):
        images, labels = test_generator[i]
        for j in range(len(images)):
            X_test_reshaped.append(images[j])
            y_test.append(labels[j])

    X_test_reshaped = np.array(X_test_reshaped)
    y_test = np.array(y_test, dtype=np.int32)

    # Add a time dimension to the input data
    X_test_reshaped = np.expand_dims(X_test_reshaped, axis=1)

    # Load the trained model
    model = load_model('lung_detection_grunot20.h5')

    # Evaluate the model on the test data
    loss, accuracy = model.evaluate(X_test_reshaped, y_test)
    print(f"Test loss: {loss}")
    print(f"Test accuracy: {accuracy}")


Found 4110 images belonging to 6 classes.


129/129 ━━━━━━━━━━━━━━━━━━━━ 16s 115ms/step - accuracy: 0.8092 - loss: 1.2073
Test loss: 1.155372142791748
Test accuracy: 0.803892970085144


In [12]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# Load the trained model
model = load_model('lung_detection_grunot20.h5')

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(f"Test loss: {loss}")
print(f"Test accuracy: {accuracy}")

# Get the raw predictions for the test data
y_pred_probs = model.predict(X_test_reshaped)

# Convert the predicted probabilities to class labels
y_pred = np.argmax(y_pred_probs, axis=1)

# Get the class labels
labels = test_generator.class_indices

# Generate the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=labels))

# Generate the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


129/129 ━━━━━━━━━━━━━━━━━━━━ 16s 114ms/step - accuracy: 0.8092 - loss: 1.2073
Test loss: 1.155372142791748
Test accuracy: 0.803892970085144
129/129 ━━━━━━━━━━━━━━━━━━━━ 15s 115ms/step

Classification Report:
              precision    recall  f1-score   support

CARDIOMEGALY       0.85      0.81      0.83       685
       COVID       0.75      0.75      0.75       685
      NORMAL       0.77      0.80      0.79       685
   PNEUMONIA       0.94      0.87      0.90       685
PNEUMOTHORAX       0.65      0.69      0.67       685
TUBERCULOSIS       0.89      0.90      0.90       685

    accuracy                           0.80      4110
   macro avg       0.81      0.80      0.81      4110
weighted avg       0.81      0.80      0.81      4110


Confusion Matrix:
[[554  47   1   2  74   7]
 [ 34 514  31   4  71  31]
 [ 18  14 550  28  64  11]
 [  7  14  49 598  13   4]
 [ 34  72  80   7 471  21]
 [  5  24   4   0  35 617]]


In [13]:
    import os
    import numpy as np
    from tensorflow.keras.models import Sequential, load_model
    from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, GRU, TimeDistributed
    from tensorflow.keras.preprocessing.image import ImageDataGenerator

    # Set the path to your dataset
    train_data_dir = r"D:\new smote\train-20230326T152931Z-001\train"

    # Specify image dimensions and batch size
    img_width, img_height = 150, 150
    batch_size = 32

    # Extract class names from the folder names
    class_names = sorted(os.listdir(train_data_dir))

    # Create data generator for training data
    train_datagen = ImageDataGenerator(
        rescale=1. / 255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

    train_generator = train_datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode='sparse',
        shuffle=False)  # Disable shuffling to maintain the order of images

    # Reshape the input data to include a time dimension
    X_train_reshaped = []
    y_train = []

    for i in range(len(train_generator)):
        images, labels = train_generator[i]
        for j in range(len(images)):
            X_train_reshaped.append(images[j])
            y_train.append(labels[j])

    X_train_reshaped = np.array(X_train_reshaped)
    y_train = np.array(y_train, dtype=np.int32)

    # Add a time dimension to the input data
    X_train_reshaped = np.expand_dims(X_train_reshaped, axis=1)

    # Define the GRU model
    model = Sequential()
    model.add(TimeDistributed(Conv2D(32, (3, 3), activation='relu'), input_shape=(1, img_width, img_height, 3)))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Conv2D(64, (3, 3), activation='relu')))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Conv2D(128, (3, 3), activation='relu')))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(TimeDistributed(Flatten()))
    model.add(GRU(128, activation='relu', return_sequences=False))
    model.add(Dense(len(class_names), activation='softmax'))

    # Compile the model
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    # Train the model
    model.fit(
        X_train_reshaped,
        y_train,
        batch_size=batch_size,
        epochs=10,
        steps_per_epoch=312)

    # Save the trained model
    model.save('lung_detection_grunot10.h5')

    # Set the path to your test dataset
    test_data_dir = r"D:\new smote\test-20230326T155708Z-001\test"

    # Create data generator for test data
    test_datagen = ImageDataGenerator(rescale=1. / 255)

    test_generator = test_datagen.flow_from_directory(
        test_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode='sparse',
        shuffle=False)  # Disable shuffling to maintain the order of images

    # Reshape the input data to include a time dimension
    X_test_reshaped = []
    y_test = []

    for i in range(len(test_generator)):
        images, labels = test_generator[i]
        for j in range(len(images)):
            X_test_reshaped.append(images[j])
            y_test.append(labels[j])

    X_test_reshaped = np.array(X_test_reshaped)
    y_test = np.array(y_test, dtype=np.int32)

    # Add a time dimension to the input data
    X_test_reshaped = np.expand_dims(X_test_reshaped, axis=1)

    # Load the trained model
    model = load_model('lung_detection_grunot10.h5')

    # Evaluate the model on the test data
    loss, accuracy = model.evaluate(X_test_reshaped, y_test)
    print(f"Test loss: {loss}")
    print(f"Test accuracy: {accuracy}")


Found 16050 images belonging to 6 classes.


C:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\core\wrapper.py:27: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 221s 576ms/step - accuracy: 0.4789 - loss: 1.3109
Epoch 2/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 109s 348ms/step - accuracy: 0.6986 - loss: 0.8362
Epoch 3/10


C:\ProgramData\anaconda3\Lib\contextlib.py:155: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


312/312 ━━━━━━━━━━━━━━━━━━━━ 182s 584ms/step - accuracy: 0.7483 - loss: 0.6669
Epoch 4/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 129s 413ms/step - accuracy: 0.7845 - loss: 0.6047
Epoch 5/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 245s 785ms/step - accuracy: 0.8419 - loss: 0.4258
Epoch 6/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 196s 626ms/step - accuracy: 0.8484 - loss: 0.4220
Epoch 7/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 332s 1s/step - accuracy: 0.9005 - loss: 0.2784
Epoch 8/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 198s 635ms/step - accuracy: 0.8891 - loss: 0.2935
Epoch 9/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 332s 1s/step - accuracy: 0.9282 - loss: 0.1931
Epoch 10/10
312/312 ━━━━━━━━━━━━━━━━━━━━ 195s 624ms/step - accuracy: 0.9281 - loss: 0.2034


Found 4110 images belonging to 6 classes.


129/129 ━━━━━━━━━━━━━━━━━━━━ 32s 219ms/step - accuracy: 0.7240 - loss: 1.1078
Test loss: 0.9522036910057068
Test accuracy: 0.7481752038002014


In [14]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# Load the trained model
model = load_model('lung_detection_grunot10.h5')

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(f"Test loss: {loss}")
print(f"Test accuracy: {accuracy}")

# Get the raw predictions for the test data
y_pred_probs = model.predict(X_test_reshaped)

# Convert the predicted probabilities to class labels
y_pred = np.argmax(y_pred_probs, axis=1)

# Get the class labels
labels = test_generator.class_indices

# Generate the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=labels))

# Generate the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


129/129 ━━━━━━━━━━━━━━━━━━━━ 28s 191ms/step - accuracy: 0.7240 - loss: 1.1078
Test loss: 0.9522036910057068
Test accuracy: 0.7481752038002014
129/129 ━━━━━━━━━━━━━━━━━━━━ 23s 173ms/step

Classification Report:
              precision    recall  f1-score   support

CARDIOMEGALY       0.89      0.66      0.76       685
       COVID       0.72      0.70      0.71       685
      NORMAL       0.85      0.62      0.71       685
   PNEUMONIA       0.90      0.90      0.90       685
PNEUMOTHORAX       0.48      0.83      0.61       685
TUBERCULOSIS       0.93      0.78      0.85       685

    accuracy                           0.75      4110
   macro avg       0.80      0.75      0.76      4110
weighted avg       0.80      0.75      0.76      4110


Confusion Matrix:
[[455  63   0   3 162   2]
 [ 24 479  10  11 143  18]
 [ 12  11 422  47 189   4]
 [  1  16  25 617  25   1]
 [ 10  51  37   4 571  12]
 [ 11  44   3   3  93 531]]
